FROM registry.redhat.io/rhel9-beta/rhel-bootc:9.4

# Copy our custom configuration in /etc/vmware-tools/tools.conf
COPY etc/ /etc/
RUN dnf -y install open-vm-tools && \
    dnf clean all && \
    systemctl enable vmtoolsd.service
