FROM registry.redhat.io/rhel10/rhel-bootc:10.1

# Copy our custom configuration in /etc/vmware-tools/tools.conf
COPY etc/ /etc/
RUN dnf -y install open-vm-tools && \
    dnf clean all && \
    systemctl enable vmtoolsd.service
